version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: agriculture-rabbitmq
    ports:
      - "5672:5672"    # AMQP port
      - "15672:15672"  # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: agriculture123
      RABBITMQ_DEFAULT_VHOST: /
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    networks:
      - agriculture-network

volumes:
  rabbitmq_data:

networks:
  agriculture-network:
    driver: bridge